name: string_ops
version: 0.0.1
description: An extension to the string class that simplifies common formatting requirements.
repository: https://github.com/baldwin-design-co/string_ops

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.8
